# Introduction {#intro}

*Streptococcus pneumoniae* is a commensal bacterium found in the nasopharynx of humans where it plays an integral part in the normal upper respiratory flora. It is also a common pathogen and is one of the most common bacterial causes of disease in humans. In classical medical texts pneumococcus is described as a Gram-positive lancet-shaped coccus that is usually found in pairs. Pneumococcus is encapsulated by a polysaccharide coating that protects it from environmental factors. The polysaccharide capsule acts as an invisibility cloak in regard to the human immune system which is rendered unable to detect pneumococcus except through certain patterns in the oligosaccharides contained within the capsule. Based on these patterns, pneumococcus has been classified into over 90 different serotypes as of the writing of this thesis. Additionally, as the capsule only contains polysaccharides and not proteins, the immune response is T cell independent and therefore poorly immunogenic even after identification by the immune system. These are the fundamental problems faced by scientists when engineering new pneumococcal vaccines. 

All serotypes of pneumococcus have the potential to cause disease in humans. However, some are more virulent than others. The prevalence of asymptomatic carriage in the nasopharynx varies greatly by serotype as does the prevalence of serotypes causing clinical infections. Quantifying the pathogenic potential of serotypes can be difficult as both need to be considered. With few exemptions, acquisition of a new serotype into the nasopharyngeal flora proceeds clinical disease caused by that serotype. Pneumococcal epidemiology is dominated by this effect, wherein children act as a reservoir of asymptomatic pneumococcal carriage from which other children and adults acquire serotypes that may lead to symptomatic disease.  Vaccinations that decrease the pneumococcal carriage in children do therefore have the potential to reduce the incidence of disease in both other unvaccinated children and adults. This phenomenon is called a herd-effect and is integral to the development of vaccination strategies to combat pneumococcal disease.

The infectious manifestations of pneumococcal disease are broadly speaking local infections of the respiratory tract and infections of previously sterile sites. They range from common to uncommon and from benign to serious. The most common infectious manifestation of pneumococcus in acute otitis media (AOM) – an infection of the middle ear. AOM is the most common reason for physician visit and antimicrobial prescription in the pediatric population. However, the disease course is benign and rarely results in permanent disability. The pathogenesis of AOM is complex and can both be caused by viral and bacterial pathogens. Bacterial AOM is most often caused by pneumococcus and Haemophilus influnzae. Acute sinusitis is another common but benign manifestation of pneumococcal disease. Pneumococcus is also a common cause of pneumonia – from which it gets its name. Pneumonia often requires hospitalization and intravenous antimicrobial treatment and can uncommonly lead to permanent disability and death. Finally, if pneumococcus gains access to normally sterile sites it may cause invasive infections. This includes bacteremia - an infection of the blood, and meningitis – an infection of the meninges. These infectious manifestations are grouped together as invasive pneumococcal disease (IPD). Whilst IPD is extremely uncommon the consequences can be disastrous. The case fatality ratio from pneumococcal meningitis in Iceland is estimated at 15.3%. 

Pneumococcus became an early target for vaccine development because of this broad range of disease caused by pneumococcus

The vaccine benefit can be quantified in two different ways. On one hand it can prevent uncommon but serious manifestations of disease and has the potential to prevent death and serious disability. On the other hand, it prevents common infections that cumulatively present a large healthcare burden due to frequent physician visits, antimicrobial prescriptions and days of work lost by parents and caregivers. 


## Clinical manifestations of *Streptococcus pneumoniae*

~ 2 pages
- Build transmission dynamics, carriage and disease mentioned in introduction
	- Short overview of mechanism by which individuals become colonized
	- Transmission dynamics, re-visit in modeling chapter
	- Asymptomatic carriage the predecessor of infections
	- Non-invasive vs. invasive infections
		- Explain relevance of differentiating the two
		- list manifestations in each category building on introduction
	- Explain that vaccines have variable impact on different manifestations
		- Use examples from the two large RCTs

### Carriage

~ 3-4 pages
- Define carriage; age-specific prevalence, serotype distribution
	- Explain that most are born carriage free
	- Evidence for co-carriage of different serotypes
	- Age at which most children acquire carriage
		- Risk factor: daycare, siblings, smoking etc.
	- Children are the main vectors of pneumococcus
	- Rate of clearance dependent on age
	- With increasing age -> increasing immunity, decreasing prevalence
	- Senescence and carriage in the elderly
- Evidence for carriage being the predecessor infections
	- Evidence of asymptomatic carriage -> main spread of disease
	- Variable propensity of serotypes to cause disease, attack-rates
- Review the Icelandic literature and changing epidemiology
	- Carriage prevalence
	- Serotype distribution
	- Risk factors
- Describe mathematical method to estimate adult carriage from observed carriage in children.

### Acute otitis media

~ 3 - 4 pages
- Define different types of otitis media; acute otitis media
	- Pathogens, estimated % caused by pneumococcus
	- Proposed mechanism by which carriage -> AOM
	- Epidemiology, both serotype and age
	- Risk factors
- Burden of disease caused by AOM; health care utilization, cost
	- Incidence and prevalence
	- GP visits, antibacterial consumption, hospitalization (?)
	- Days of work-lost by parents
	- Sequelae; multiple infections, effusion, tympanostomies 
	- Evidence of benefit of delaying 1st presentation
-  Review of Icelandic literature and changing epidemiology
	- AOM prevalence and serotype distribution
	- Risk factors
	- Associated healthcare consumption, cost
	- Rate of sequelae

### Pneumonia

~ 4 – 5 pages
- Define: CAP, nosocomial, PP, NBPP and IPP. 
	- Pathogens, estimated % caused by pneumococcus
	- Proposed mechanism by which carriage -> pneumonia
	- Epidemiology, both serotype and age
	- Risk factors
- Burden of disease caused by pneumonia, health care utilization
	- Ways of defining severity; CURB-65 etc. 
	- GP visits, antibacterial consumption, Hospitalization rates
	- Days of work lost	
	- Mortality, sequelae
-  Review of Icelandic literature and changing epidemiology
	- Pneumococcal pneumonia prevalence and serotype distribution
	- Rate of hospitalization, healthcare consumption
	- Rate of sequelae
	- Risk factors

### Invasive pneumococcal disease

~ 3 -5 pages
- Define different presentations of IPD: meningitis, bacteremia, etc.
	- Epidemiology, both serotype and age
	- Risk factors
	- Burden of disease, health care utilization
		- Severity
		- Hospitalization rates, ICU rates
		- Sequelae
-  Review of Icelandic literature and changing epidemiology
	- Meningitis, bacteremia, empyema, joint infection prevalence and 		   serotype distribution
	- Rate of sequelae


## Pneumococcal conjugate vaccines

~ 1 -2 pages
- PPSV23 original studies, downsides, immunogenicity
- Development of protein conjugate vaccines, reasons
- PCV7
- Higher valency PCVs 

## Impact of pneumococcal conjugate vaccines

~ 3 pages
- Present evidence of magnitude of effect on VT carriage
	- Serotype distribution vs. carriage prevalence
		- Serotype replacement 
	- Herd-effect, i.e. effect on carriage of adults and non-vaccinated


### Acute otitis media

~ 1-2 pages <- much fewer studies
- Present evidence of magnitude of effect on all-cause AOM
	- VT vs. NVT serotypes
		- Serotype replacement (?)	
	- Herd-effect in non-vaccinated


### Pneumonia

~ 2-3 pages
- Present evidence of effect on all-cause pneumonia
	- VT vs. NVT serotypes
		- Serotype replacement (?)
	 - Herd-effect in adults and non-vaccinated


### Invasive pneumococcal disease

~ 4-6 pages <- largest amount of studies
- Present evidence of effect on IPD and subgroups; meningitis, bacteremia etc. 
	- VT vs. NVT
	- Serotype replacement
	- Herd-effect

## Cost-effectiveness of pneumococcal conjugate vaccination

~ 3-4 pages
- Present overview of literature review and critical analysis. 
- Recommendations of ISPOR and WHO presented, discuss importance of assumptions and methodology
- Introduction to sub-chapters of lit. rev. 
	- Explain how they will be tied in to ISPOR/WHO recommendations


### Measurement of effectiveness and choice of health outcomes

~ 1 page
- Shortly explain what is meant by effectiveness and health outcomes
	- Tie in to ISPOR/WHO

#### Health outcomes considered

~ 2-3 pages
- Describe what health outcomes were considered
	- Tie into actual disease burden known to be caused by pneumococcus
	
#### Effectiveness of PCV7

~ 3-4 pages
- What effectiveness rationale is used, methods and rationale: critique
		- Carriage
		- AOM
		- Pneumonia
		- IPD


#### Effectiveness of PCV10

~2-3 pages
- What effectiveness rationale is used, methods and rationale: critique
		- Carriage
		- AOM
		- Pneumonia
		- IPD

#### Effectiveness of PCV13

~ 2- 3 pages
- What effectiveness rationale is used, methods and rationale: critique
		- Carriage
		- AOM
		- Pneumonia
		- IPD


### Estimating resources and cost


~1 page
- Shortly explain what resources and costs mean
	- Direct vs. indirect
	- Tie in to ISPOR/WHO
