# Materials and methods {#methods}

## Data collection and sources

Data was collected from multiple whole population registries and a single hospital registry for the study period from the 1st of January 2005 to the 31st of December 2017.
All data was identifiable to the individual level based on governmental issued national identification numbers. 
Every Icelandic resident is issued a national indentification number at birth or when granted residency.
The national indentification number is a ten-digit numerical sequence.
The first six numbers represent the individual’s date of birth in the form dd/mm/yy.
The tenth digit represents the century in which the individual was born, e.g. the national indentification number for a person born in 1970 would end in nine.
Digits seven through nine are generated individually through a random sequence.
A national indentification number is not reused upon the death of the individual, and each individual receives one and only one number over the course of their lifetime.
The national indentification number can therefore be used to accurately identify a unique individual through different administrative databases and through time.
Though the national indentification number was used as the basis to identify unique individuals and link across multiple data sets, the researchers did not receive the numbers directly.
Rather, all datasets were first sent to the Directorate of Health where staff anonymized the data and created unique study identification numbers.
The data was then released to the researchers.
These unique study identification numbers will be referred to as study IDs in all further chapters of this thesis. 

The data used in this study benefits from the stability of its sources.
Electronic medical records have been used ubiquitously in Iceland from the beginning of the period.
The same electronic medical record software, Saga, was used by all health-care providers and institutions during the whole study period.
One diagnostic coding system, The International Classification of Diseases version 10, has been in use during the whole study period and procedures have always been classified using the NOMESCO Classification of Surgical Procedures. 
Drugs are classified using the Anatomical-Therapeutic-Chemical (ATC) classification system of the World Health Organization. 

Each database included the same demographic data with few exceptions.
The common demographic data will be described here and discrepancies from this will be noted in the relevant subchapter for the specific dataset.
Common demographic data included the following; gender, date of birth, and age and legal residence at the time of the recorded observation. 
Legal residence was aggregated to the postal code.
Hereafter, each administrative data set will be described in detail.

The Directorate of Health

The Icelandic Directorate of Health is responsible for the collection and maintenance of several whole population registries used in this thesis.
They are; the National Drug Prescription Database (NDPD), the National Vaccine Registry (NVR) and the Primary Care Database (PCD).
Furthermore, staff of the Directorate of Health were responsible for the anonymization of all the study data and the creation of study IDs. 

The National Drug Prescription Database

The NDPD is a whole population database collected and maintained by the Icelandic Directorate of Health from the 1st of January 2005.
It contains information on all filled drug prescriptions in Iceland.
All pharmacies are required by law to collect data on each filled prescription and submit this to the NDPD.
An important distinction must be made between a filled prescription and a prescription.
The NDPD receives information if and when a prescription is filled.
This means that the NDPD does not contain information on prescriptions that were never filled by the patient.
This also means that all prescriptions contained within the NDPD were bought and received by the patient.
Extensive validation and error testing has been performed by the Directorate of Health to ensure the robustness and coverage of the NDPD.
The submission to the NDPD has been automated electronically and coupled with the process by which drugs are dispensed at the pharmacies, essentially excluding the possibility of a filled prescription not being registered. The NDPD included demographic data as previously described.

The Primary Care Database

