--- 
title: "PhD thesis"
author: "Elías Sæbjörn Eyþórsson"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [library.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: eliaseythorsson/phd_thesis
description: "This is a PhD thesis written in real-time in Rstudio"
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE, error = FALSE, message = FALSE, warning = FALSE)
library(knitr)
library(tidyverse)

# automatically create a bib database for R packages
knitr::write_bib(
    c(
    .packages(),
    'tidyverse',
    'bookdown',
    'knitr',
    'rmarkdown',
    'epiR',
    'survival',
    'rms',
    'survminer',
    'pogit',
    'kableExtra'
    ),
    'packages.bib'
    )
```

```{r table-abbreviations}
data_frame(
    Term = c(
    "Acute otitis media",
    "Community-acquired pneumonia",
    "Hospital-aquired pneumonia",
    "Respiratory syncytial virus",
    "Enzyme-linked immunosorbent assay",
    "International Classification of Diseases, 10th revision",
    "NOMESCO Classification of Surgical Procedures",
    "Anatomical-Therapeutic-Chemical",
    "National Drug Prescription Registry",
    "Incidence rate",
    "Incidence rate ratio",
    "National Vaccine Registry",
    "Vaccine non-eligible cohorts",
    "Vaccine eligible cohorts",
    "Confidence intervals",
    "Hazard ratio",
    "Tympanostomy tube placement",
    "Upper respiratory tract infection",
    "Lower respiratory tract infection",
    "Invasive pneumococcal disease",
    "Intensive care unit",
    "Principal component analysis",
    "Seasonal and trend decompisition using LOESS",
    "Leave-one-out cross-validation",
    "Organisation for Economic Co-operation and Development",
    "Quality-adjusted life-years",
    "International Society for Pharmacoeconomics and Outcome Research",
    "Cost-benefit analysis",
    "Cost-effectiveness analysis",
    "Cost-utility analysis",
    "23-valent pneumococcal polysaccharide vaccine",
    "Pneumococcal conjugate vaccine",
    "7-valent pneumococcal conjugate vaccine",
    "10-valent pneumococcal conjugate vaccine",
    "11-valent pneumococcal conjugate vaccine",
    "13-valent pneumococcal conjugate vaccine",
    "Cost-effectiveness acceptability curve",
    "Probabilistic sensitivity analysis", 
    "Meningococcal outer membrane protein complex",
    "Case-fatality ratio",
    "non-typable Haemophilus influenzae",
    "Icelandic krona",
    "10-valent pneumococcal *Haemophilus influnzae* protein-D conjugate vaccine "
    ),
    Abbreviation = c(
    "AOM",
    "CAP",
    "HAP",
    "RSV",
    "ELISA",
    "ICD-10",
    "NCSP",
    "ATC",
    "NDPR",
    "IR",
    "IRR",
    "NVR",
    "VNEC",
    "VEC",
    "CI",
    "HR",
    "TTP",
    "URTI",
    "LRTI",
    "IPD",
    "ICU",
    "PCA",
    "STL",
    "LOOCV",
    "OECD",
    "QALY",
    "ISPOR",
    "CBA",
    "CEA",
    "CUA",
    "PPV-23",
    "PCV",
    "PCV7",
    "PCV10",
    "PCV11",
    "PCV13",
    "CEAC",
    "PSA", 
    "MOMPC",
    "CFR",
    "NTHi",
    "ISK",
    "PHiD-CV10"
    )
    ) %>%
    arrange(Abbreviation) %>% # i.e. alphabetical order by Term
    kable(booktab = T, caption = "List of abbreviations")
```
